# Site settings
title:          Data Science mit R - Wie schreibe ich eine erfolgreiche Dissertation?
description:    "Online Material zum Kurs Data Science mit R - Verstehen und Auswerten von klinischen Daten"
url:            "https://felix-popp.github.io"



# Author
author:
  name:         Felix Popp
  email:        felix.c.popp@googlemail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
#disqus:         jekyll-tale
